### ISSUE TITLE
ASCII codec failed.

### ISSUE THREAD

**Issue by kyroskoh** [arghblargh/QueueBot#5]
Traceback (most recent call last):
  File "QueueBot.py", line 433, in <module>
    main()
  File "QueueBot.py", line 209, in main
    readbuffer += s.recv(1024).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 60: ordinal not in range(128)

**Comment by kyroskoh** [comment]
Then, I have edit the code: 

```
            # Receive data from IRC and spitting it into lines.
            readbuffer += s.recv(1024).decode()
```

to:

```
            # Receive data from IRC and spitting it into lines.
            readbuffer += s.recv(1024).decode('utf-8', 'ignore')
```

---

It looks fine for time being... Still monitoring...
